version: '2'
services:
  mongodb:
    image: "mongo"
    command: "--smallfiles"
    ports:
      - "27017:27017"
    
  backend:
    build: ./server/
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./front-end/
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/usr/src/app
    depends_on:
      - backend
